usuarios:
{
	[
		{
			"email": "usuario1@correo.com",
			"contrasena": "1234",
			"nombre": "Angel",
			"identificacion": "1111111",
			"telefono": "3282345657",
		},

		{
			"email": "usuario2@correo.com",
			"contrasena": "1234",
			"nombre": "Andres",
			"identificacion": "2222222",
			"telefono": "3282345657",
		},

		{
			"email": "usuario3@correo.com",
			"contrasena": "1234",
			"nombre": "Daniel",
			"identificacion": "333333",
			"telefono": "3282345657",
		},

		{
			"email": "usuario4@correo.com",
			"contrasena": "1234",
			"nombre": "Miguel",
			"identificacion": "44444444",
			"telefono": "3282345657",
		},

		{
			"email": "usuario5@correo.com",
			"contrasena": "1234",
			"nombre": "Julian",
			"identificacion": "55555555",
			"telefono": "3282345657",
		},
	]
}





inmuebles:
{
	[
		{
			"idInmueble": 1,
			"propietario": "usuario2@correo.com",
			"titulo": "Inmueble1",
			"descripcion": "Arriendo Inmueble bonito",
			"especificaciones": {
				"ciudad": "Bucaramanga",
				"direccion": "calle 91#39-4",
				"tipoInmueble": "Apartamento",
				"valorArriendo": 1575639,
				"valorAdmin": 175074,
				"tamaño": 73,
				"estrato": 1,
				"habitaciones": 5,
				"baños": 2,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "22-08-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},	

		{
			"idInmueble": 2,
			"propietario": "usuario5@correo.com",
			"titulo": "Inmueble2",
			"descripcion": "Arriendo Inmueble nuevo",
			"especificaciones": {
				"ciudad": "Medellin",
				"direccion": " 34#8-24",
				"tipoInmueble": "Casa",
				"valorArriendo": 1713142,
				"valorAdmin": 166126,
				"tamaño": 137,
				"estrato": 2,
				"habitaciones": 3,
				"baños": 3,
				"parqueadero": true,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "17-09-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},		

		{
			"idInmueble": 3,
			"propietario": "usuario1@correo.com",
			"titulo": "Inmueble3",
			"descripcion": "Arriendo Inmueble grande",
			"especificaciones": {
				"ciudad": "Cali",
				"direccion": "calle 32#33-45",
				"tipoInmueble": "Apartamento",
				"valorArriendo": 1569404,
				"valorAdmin": 178529,
				"tamaño": 65,
				"estrato": 3,
				"habitaciones": 4,
				"baños": 2,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "28-10-2022",
			"arrendatario": "usuario3@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},			

		{
			"idInmueble": 4,
			"propietario": "usuario1@correo.com",
			"titulo": "Inmueble4",
			"descripcion": "Arriendo Inmueble nuevo",
			"especificaciones": {
				"ciudad": "Bogota",
				"direccion": " 98#31-35",
				"tipoInmueble": "Local",
				"valorArriendo": 1953332,
				"valorAdmin": 84435,
				"tamaño": 139,
				"estrato": 3,
				"habitaciones": 3,
				"baños": 2,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "17-09-2022",
			"arrendatario": "usuario5@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},				

		{
			"idInmueble": 5,
			"propietario": "usuario4@correo.com",
			"titulo": "Inmueble5",
			"descripcion": "Arriendo Inmueble lujoso",
			"especificaciones": {
				"ciudad": "Cali",
				"direccion": " 72#20-11",
				"tipoInmueble": "Local",
				"valorArriendo": 2653640,
				"valorAdmin": 153045,
				"tamaño": 122,
				"estrato": 4,
				"habitaciones": 2,
				"baños": 3,
				"parqueadero": true,
			},
			"estadoPublicacion": "Borrador",
			"fechaPublicacion": "28-10-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},			

		{
			"idInmueble": 6,
			"propietario": "usuario5@correo.com",
			"titulo": "Inmueble6",
			"descripcion": "Arriendo Inmueble bonito",
			"especificaciones": {
				"ciudad": "Bogota",
				"direccion": " 40#42-35",
				"tipoInmueble": "Apartaestudio",
				"valorArriendo": 2620652,
				"valorAdmin": 127485,
				"tamaño": 168,
				"estrato": 3,
				"habitaciones": 5,
				"baños": 4,
				"parqueadero": false,
			},
			"estadoPublicacion": "Borrador",
			"fechaPublicacion": "10-10-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},	

		{
			"idInmueble": 7,
			"propietario": "usuario3@correo.com",
			"titulo": "Inmueble7",
			"descripcion": "Arriendo Inmueble nuevo",
			"especificaciones": {
				"ciudad": "Cali",
				"direccion": "calle 53#17-25",
				"tipoInmueble": "Apartamento",
				"valorArriendo": 1995464,
				"valorAdmin": 174081,
				"tamaño": 115,
				"estrato": 2,
				"habitaciones": 6,
				"baños": 4,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "22-08-2022",
			"arrendatario": "usuario4@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},			

		{
			"idInmueble": 8,
			"propietario": "usuario4@correo.com",
			"titulo": "Inmueble8",
			"descripcion": "Arriendo Inmueble barato",
			"especificaciones": {
				"ciudad": "Bogota",
				"direccion": "calle 28#39-13",
				"tipoInmueble": "Local",
				"valorArriendo": 1085317,
				"valorAdmin": 112872,
				"tamaño": 191,
				"estrato": 1,
				"habitaciones": 5,
				"baños": 3,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "10-10-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},					

		{
			"idInmueble": 9,
			"propietario": "usuario2@correo.com",
			"titulo": "Inmueble9",
			"descripcion": "Arriendo Inmueble barato",
			"especificaciones": {
				"ciudad": "Bogota",
				"direccion": " 92#46-44",
				"tipoInmueble": "Apartamento",
				"valorArriendo": 1020362,
				"valorAdmin": 90774,
				"tamaño": 86,
				"estrato": 2,
				"habitaciones": 4,
				"baños": 4,
				"parqueadero": true,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "17-09-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},		

		{
			"idInmueble": 10,
			"propietario": "usuario5@correo.com",
			"titulo": "Inmueble10",
			"descripcion": "Arriendo Inmueble lujoso",
			"especificaciones": {
				"ciudad": "Medellin",
				"direccion": " 9#23-12",
				"tipoInmueble": "Local",
				"valorArriendo": 2014942,
				"valorAdmin": 128538,
				"tamaño": 66,
				"estrato": 2,
				"habitaciones": 1,
				"baños": 4,
				"parqueadero": true,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "22-08-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},				

		{
			"idInmueble": 11,
			"propietario": "usuario3@correo.com",
			"titulo": "Inmueble11",
			"descripcion": "Arriendo Inmueble barato",
			"especificaciones": {
				"ciudad": "Bogota",
				"direccion": "calle 54#5-45",
				"tipoInmueble": "Casa",
				"valorArriendo": 1157623,
				"valorAdmin": 148724,
				"tamaño": 106,
				"estrato": 4,
				"habitaciones": 2,
				"baños": 2,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "10-10-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},				

		{
			"idInmueble": 12,
			"propietario": "usuario2@correo.com",
			"titulo": "Inmueble12",
			"descripcion": "Arriendo Inmueble grande",
			"especificaciones": {
				"ciudad": "Bogota",
				"direccion": "calle 79#25-13",
				"tipoInmueble": "Apartaestudio",
				"valorArriendo": 924481,
				"valorAdmin": 120566,
				"tamaño": 126,
				"estrato": 2,
				"habitaciones": 5,
				"baños": 3,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "10-10-2022",
			"arrendatario": "usuario2@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},				

		{
			"idInmueble": 13,
			"propietario": "usuario1@correo.com",
			"titulo": "Inmueble13",
			"descripcion": "Arriendo Inmueble barato",
			"especificaciones": {
				"ciudad": "Bogota",
				"direccion": "carrera 91#35-29",
				"tipoInmueble": "Apartaestudio",
				"valorArriendo": 1547979,
				"valorAdmin": 90878,
				"tamaño": 80,
				"estrato": 5,
				"habitaciones": 5,
				"baños": 2,
				"parqueadero": true,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "10-10-2022",
			"arrendatario": "usuario2@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},				

		{
			"idInmueble": 14,
			"propietario": "usuario2@correo.com",
			"titulo": "Inmueble14",
			"descripcion": "Arriendo Inmueble bonito",
			"especificaciones": {
				"ciudad": "Medellin",
				"direccion": "calle 69#34-48",
				"tipoInmueble": "Apartamento",
				"valorArriendo": 1178164,
				"valorAdmin": 84289,
				"tamaño": 114,
				"estrato": 1,
				"habitaciones": 3,
				"baños": 4,
				"parqueadero": true,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "01-10-2022",
			"arrendatario": "usuario5@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},			

		{
			"idInmueble": 15,
			"propietario": "usuario5@correo.com",
			"titulo": "Inmueble15",
			"descripcion": "Arriendo Inmueble grande",
			"especificaciones": {
				"ciudad": "Cali",
				"direccion": "calle 2#49-5",
				"tipoInmueble": "Apartamento",
				"valorArriendo": 1513649,
				"valorAdmin": 101444,
				"tamaño": 144,
				"estrato": 5,
				"habitaciones": 2,
				"baños": 3,
				"parqueadero": true,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "17-09-2022",
			"arrendatario": "usuario3@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},				

		{
			"idInmueble": 16,
			"propietario": "usuario5@correo.com",
			"titulo": "Inmueble16",
			"descripcion": "Arriendo Inmueble lujoso",
			"especificaciones": {
				"ciudad": "Medellin",
				"direccion": "calle 53#29-26",
				"tipoInmueble": "Apartaestudio",
				"valorArriendo": 1496844,
				"valorAdmin": 86793,
				"tamaño": 83,
				"estrato": 3,
				"habitaciones": 2,
				"baños": 1,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "28-10-2022",
			"arrendatario": "usuario2@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},						

		{
			"idInmueble": 17,
			"propietario": "usuario5@correo.com",
			"titulo": "Inmueble17",
			"descripcion": "Arriendo Inmueble bonito",
			"especificaciones": {
				"ciudad": "Cali",
				"direccion": "calle 99#30-11",
				"tipoInmueble": "Casa",
				"valorArriendo": 1235915,
				"valorAdmin": 104620,
				"tamaño": 69,
				"estrato": 4,
				"habitaciones": 5,
				"baños": 3,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "22-08-2022",
			"arrendatario": "usuario2@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},		
		
		{
			"idInmueble": 18,
			"propietario": "usuario2@correo.com",
			"titulo": "Inmueble18",
			"descripcion": "Arriendo Inmueble grande",
			"especificaciones": {
				"ciudad": "Medellin",
				"direccion": "calle 87#28-13",
				"tipoInmueble": "Local",
				"valorArriendo": 1743848,
				"valorAdmin": 145616,
				"tamaño": 160,
				"estrato": 5,
				"habitaciones": 2,
				"baños": 3,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "28-10-2022",
			"arrendatario": "usuario2@correo.com",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},				

		{
			"idInmueble": 19,
			"propietario": "usuario4@correo.com",
			"titulo": "Inmueble19",
			"descripcion": "Arriendo Inmueble barato",
			"especificaciones": {
				"ciudad": "Medellin",
				"direccion": "carrera 81#22-24",
				"tipoInmueble": "Local",
				"valorArriendo": 1110372,
				"valorAdmin": 123189,
				"tamaño": 152,
				"estrato": 1,
				"habitaciones": 1,
				"baños": 2,
				"parqueadero": false,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "22-08-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},	

		{
			"idInmueble": 20,
			"propietario": "usuario4@correo.com",
			"titulo": "Inmueble20",
			"descripcion": "Arriendo Inmueble nuevo",
			"especificaciones": {
				"ciudad": "Bucaramanga",
				"direccion": " 6#6-17",
				"tipoInmueble": "Apartaestudio",
				"valorArriendo": 1559171,
				"valorAdmin": 86855,
				"tamaño": 188,
				"estrato": 3,
				"habitaciones": 2,
				"baños": 4,
				"parqueadero": true,
			},
			"estadoPublicacion": "Publicado",
			"fechaPublicacion": "22-08-2022",
			"arrendatario": "",
			"fotos": {
				0: "",
				1: "",
				2: "",
				3: "",
				4: "",
				5: "",
				6: "",
				7: "",
				8: "",
				9: "",
				10: "",
				11: "",
				12: "",
				13: "",
				14: "",
				15: "",
			}
		},					
	]
}







contratos:
{
	[
		{
			"idContrato": 1,
			"idInmueble": 3,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "28-10-2022",
			"propietario": "usuario1@correo.com",
			"arrendatario": "usuario3@correo.com",
			"duracion": 6,
			"valorArriendo": 1569404,
			"valorAdmin": 178529,
			"activo": true,
			"fechaTerminacion": "",
		},

		{
			"idContrato": 2,
			"idInmueble": 4,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "17-09-2022",
			"propietario": "usuario1@correo.com",
			"arrendatario": "usuario5@correo.com",
			"duracion": 6,
			"valorArriendo": 1953332,
			"valorAdmin": 84435,
			"activo": true,
			"fechaTerminacion": "",
		},

		{
			"idContrato": 3,
			"idInmueble": 7,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "22-08-2022",
			"propietario": "usuario3@correo.com",
			"arrendatario": "usuario4@correo.com",
			"duracion": 6,
			"valorArriendo": 1995464,
			"valorAdmin": 174081,
			"activo": true,
			"fechaTerminacion": "",
		},

		{
			"idContrato": 4,
			"idInmueble": 12,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "10-10-2022",
			"propietario": "usuario2@correo.com",
			"arrendatario": "usuario2@correo.com",
			"duracion": 6,
			"valorArriendo": 924481,
			"valorAdmin": 120566,
			"activo": true,
			"fechaTerminacion": "",
		},

		{
			"idContrato": 5,
			"idInmueble": 13,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "10-10-2022",
			"propietario": "usuario1@correo.com",
			"arrendatario": "usuario2@correo.com",
			"duracion": 6,
			"valorArriendo": 1547979,
			"valorAdmin": 90878,
			"activo": true,
			"fechaTerminacion": "",
		},

		{
			"idContrato": 6,
			"idInmueble": 14,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "01-10-2022",
			"propietario": "usuario2@correo.com",
			"arrendatario": "usuario5@correo.com",
			"duracion": 6,
			"valorArriendo": 1178164,
			"valorAdmin": 84289,
			"activo": true,
			"fechaTerminacion": "",
		},

		{
			"idContrato": 7,
			"idInmueble": 15,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "17-09-2022",
			"propietario": "usuario5@correo.com",
			"arrendatario": "usuario3@correo.com",
			"duracion": 6,
			"valorArriendo": 1513649,
			"valorAdmin": 101444,
			"activo": true,
			"fechaTerminacion": "",
		},

		{
			"idContrato": 8,
			"idInmueble": 16,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "28-10-2022",
			"propietario": "usuario5@correo.com",
			"arrendatario": "usuario2@correo.com",
			"duracion": 6,
			"valorArriendo": 1496844,
			"valorAdmin": 86793,
			"activo": true,
			"fechaTerminacion": "",
		},

		{
			"idContrato": 9,
			"idInmueble": 17,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "22-08-2022",
			"propietario": "usuario5@correo.com",
			"arrendatario": "usuario2@correo.com",
			"duracion": 6,
			"valorArriendo": 1235915,
			"valorAdmin": 104620,
			"activo": true,
			"fechaTerminacion": "",
		},

		{
			"idContrato": 10,
			"idInmueble": 18,
			"fechaContrato": "01-11-2022",
			"fechaPublicacion": "28-10-2022",
			"propietario": "usuario2@correo.com",
			"arrendatario": "usuario2@correo.com",
			"duracion": 6,
			"valorArriendo": 1743848,
			"valorAdmin": 145616,
			"activo": true,
			"fechaTerminacion": "",
		},
	]
}



